name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - first_test
          - second_test
          - all


  test:
    runs-on: ubuntu-latest
    needs: download-history

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: first_test
        if: "github.event.inputs.deployment_target == 'first_test'"
        run: pytest tests\feature_profile_test.py
        continue-on-error: true
      - name: second_test
        if: "github.event.inputs.deployment_target == 'second_test'"
        run: pytest
